name = "FastScape"
uuid = "873e0edb-522b-45b6-bc89-e98bcd41d702"
authors = ["Boris Kaus <kaus@uni-mainz.de>"]
version = "0.1.0"

[deps]
Fastscapelib_jll = "85b6c75f-dabe-5cb8-ba5f-2ccb8070923d"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
PlotsExt = "Plots"

[compat]
DelimitedFiles = "1"
Fastscapelib_jll = "2.8"
Statistics = "1.0"
WriteVTK = "1"
julia = "1.9"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Statistics", "DelimitedFiles"]
